
name: noclouds
channels:
  - conda-forge
dependencies:
  - python>=3.9
  - numpy
  - dask
  - numba
  - xarray
  - rioxarray
  - xgboost
  - pip
  - pip:
      - git+https://github.com/lewistrotter/noclouds.git